version: "3.8"

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "${NEXTCLOUD_PORT}:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_HOST=${NEXTCLOUD_DB_HOST}
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    restart: unless-stopped

volumes:
  nextcloud_data:
